name: GitHub Pages

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test
        run: make test_pkg

  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
    if: startsWith(github.event.ref, 'refs/tags/v')
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Set up Go 1.17.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: make
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
